spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

server:
  address: 0.0.0.0
  port: 10000